# kyverno-background-vpa-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-background-vpa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-vpa-access
subjects:
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno


